### ISSUE TITLE
ModuleNotFoundError: No module named 'notify2'

### ISSUE THREAD

**Issue by beertastic** [bluppfisk/coinprice-indicator#61]
I've run your exact instructions on an Ubuntu 18.04
I get this error:
ModuleNotFoundError: No module named 'notify2'

I'm not a python dev or know what is going on here.. any thoughts on this bug when I rollow your steps and get this error after I use

./run.sh

Cheers!

**Comment by bluppfisk** [comment]
Hi @beertastic, there seems to be a bit of trouble with the dependencies. I'm going to try setting up an empty container in which I can experiment and see what works best, but I'm a bit low on time. For now you can probably activate the virtualenv (`source bin/activate`) and then run `pip3 install notify2`. That might fix it. Let me know how you fare.

**Comment by beertastic** [comment]
Sadly, no effect.. (Had to install pip3 first)
But no, here is my new error:

Traceback (most recent call last):
  File "coin/coin.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'


I tried to run pip2 install yaml
I got this error:

Collecting yaml
  Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml

**Comment by bluppfisk** [comment]
This is a Python3 app. Running pip2 is for Python2. Please try with Python3 and make sure you're in the virtual environment! Please post output, too.

**Comment by beertastic** [comment]
I meant pip3... sorry.. UK based here,.. coffee still in hand and not in blood yet.

**Comment by beertastic** [comment]
On my ubuntu machine, when I run `source bin/activate`
I get this: (coinprice-indicator) 
BEFORE my user@machine prompt.. is that meaning I'm in the VE?

**Comment by bluppfisk** [comment]
That's correct :)

**Comment by beertastic** [comment]
Cool... so, yes, I'm in the correct VE ... to confirm, ths is my new error:

Collecting yaml
Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml

**Comment by bluppfisk** [comment]
Can you try `pip3 install pyyaml` instead?

I was under the impression people drank tea in the UK :)

**Comment by beertastic** [comment]
I get this:

Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages

**Comment by beertastic** [comment]
Morning coffee.. afternoon tea.. I think that's the rule :)

**Comment by bluppfisk** [comment]
Oh good rule!
How about if you run `./coin/coin.py` now? :octopus: 
I'm a bit at my wits' end here. Perhaps I should read up on how Python dependencies work.

**Comment by bluppfisk** [comment]
(while in the venv)

**Comment by beertastic** [comment]
Traceback (most recent call last):
  File "./coin/coin.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

it's all good.. I do check the sites often for prices (Come on XRP) or just shout COX from the rooftops!

**Comment by bluppfisk** [comment]
your neighbours (<-- look, a 'u') are of the understanding kind!

I will have look into the problem, but currently not enough time to do so. You'll hear about it here when I find a solution!

**Comment by bluppfisk** [comment]
Hi @beertastic: if you're still attempting to use the software, I think the new release might fix it a bit.  Perhaps your version of Python does not include vext. I'm currently on Python3.7 but Python3.6 worked fine too. Can you remove the lib, bin and share directories and try installing again? You could also run the various statements in install.sh manually.
