### ISSUE TITLE
./install.sh: line 6: vext: command not found

### ISSUE THREAD

**Issue by eehlers** [bluppfisk/coinprice-indicator#63]
after i do git clone, i attempt to install as per the documentation, this fails with:

./install.sh: line 6: vext: command not found

**Comment by bluppfisk** [comment]
That probably means vext was not installed from the requirements. You may want to try running it again or install it with `pip3 install vext` (while you're in the virtual environment and have it activated).

I unfortunately don't currently have time to try replicating your situation but the above might work?

**Comment by bluppfisk** [comment]
Hi @eehlers , I've been toying with it again. Perhaps your version of Python does not include vext. I'm currently on Python3.7 but Python3.6 worked fine too. Can you remove the lib, bin and share directories and try installing again? You could also run the various statements in install.sh manually.
