### ISSUE TITLE
How to remove this app

### ISSUE THREAD

**Issue by paul-onof** [bluppfisk/coinprice-indicator#66]
Hi,

I tried to install this on my fedora but then I found another app for gnome shell...
How could I remove this app please ?

Thanks for your help.

**Comment by bluppfisk** [comment]
Hi Paul


Just remove the folder where you put it :)

/S

**Comment by RichterGB** [comment]
What about the icon created by the system? can we remove it?
![image](https://user-images.githubusercontent.com/88848954/141020503-447c582c-e083-439b-8a8a-1447f5f3f216.png)

**Comment by bluppfisk** [comment]
Hello Paul


remove /usr/share/applications/coindicator.desktop

It will probably take a little while for this to take effect as it is
cached.


Best regards,

--
Sander Van de Moortel
Communication and IT
NL - EN - SV - FR - DE - ZH

+32 473 888 408 (Belgium)
skype: sandervdm
