### ISSUE TITLE
doesn't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by gavinito** [bluppfisk/coinprice-indicator#67]
(coinprice-indicator) gavin@Inspiron:~/coinprice-indicator$ ./install.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+20.04.20200408.1-0ubuntu1).
gir1.2-gtk-3.0 is already the newest version (3.24.18-1ubuntu1).
libcairo2-dev is already the newest version (1.16.0-4ubuntu1).
libdbus-glib-1-2 is already the newest version (0.110-5fakssync1).
python3-venv is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Collecting certifi==2018.8.24
  Using cached certifi-2018.8.24-py2.py3-none-any.whl (147 kB)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.0.4)
Collecting idna==2.7
  Using cached idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting notify2==0.3.1
  Using cached notify2-0.3.1-py2.py3-none-any.whl (8.0 kB)
Collecting pygame==1.9.4
  Using cached pygame-1.9.4.tar.gz (4.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/gavin/coinprice-indicator/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-814taf_z/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-814taf_z/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-814taf_z/pygame/pip-egg-info
         cwd: /tmp/pip-install-814taf_z/pygame/
    Complete output (12 lines):
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by gavinito** [comment]
fixed when install these manually first.
sudo apt-get build-dep python-pygame
sudo apt-get install python-dev

**Comment by bluppfisk** [comment]
glad you found a way to fix it. I'm a bit loth to change the install scripts since that worked for me on a clean install of Ubuntu 20.04, but I could probably do with a good introduction to distributing python programs :)

**Comment by bluppfisk** [comment]
Actually; nonsense. I hadn't tried on a fresh 20.04 yet but only on a fresh 19.10. It's this heat. I've now changed the requirements and install scripts which should allow installation on Ubuntu 20.04 Focal Fossa. Thanks for reporting @gavinito
