### ISSUE TITLE
work on XFCE?

### ISSUE THREAD

**Issue by lionzin** [bluppfisk/coinprice-indicator#69]
Does it work on XFCE? I tried to install it on kali linux and I can see the coin symbol, but not the price. if right click on coin icon i can see the price

**Comment by bluppfisk** [comment]
It should work on any desktop environment that supports AppIndicators. However, how it is displayed may be up to the DE. Can you post a screenshot of how it looks on your side?

**Comment by bluppfisk** [comment]
You may need something like this: https://goodies.xfce.org/projects/panel-plugins/xfce4-xfapplet-plugin. I'm not sure though as I don't have XFCE around at the moment. I'd be grateful if you could try :)

**Comment by lionzin** [comment]
Ty, 
I will try to install the plugin you recommended and I will reply soon
screenshot: https://imgur.com/hFo5i9I.png

**Comment by bluppfisk** [comment]
Assuming this works for you now. Please reopen if I can do anything else.
