### ISSUE TITLE
number price next to cryptocurrency icon not being displayed

### ISSUE THREAD

**Issue by Fallast** [bluppfisk/coinprice-indicator#85]
![image](https://user-images.githubusercontent.com/61057195/126049022-d6f79676-fc9e-4e7c-98bf-32d7fe4bd31f.png)

the panel im using is Tint2, i also tried with xfce-panel but its not showing up either, only the icons

**Comment by bluppfisk** [comment]
Hi Brian


Do you have examples of app indicators that do have labels on this shell? It may simply not support it or need a setting.

**Comment by Fallast** [comment]
you are right its not supported
